### PR TITLE
Alexa dev

### PR DESCRIPTION
**Pull request by HAXHER**
REVISION TO MAKE MERCH ON MY PART THE SERVER CODE UNTIL THE ENTIRE LOBBY PROCESS IS ALREADY DONE 

PS: in other parts add Daniel's code or in the client for anything better remove it from the merch that is 
 can do in main XD

### CODE REVIEW

**Comment by dalopezt** [comment]
Testing locally.

**Comment by dalopezt** [comment]
# **Results of testing**
### Test batch 1
- Clients can send their names ```OK```
- Server can save the names and create the Player objects ```OK```
- If the current number of clients is less than the minimum defined (in this version, defined as 8) ```OK```
- If the current number of clients is in a valid range, the server sends a broadcast message ```OK```
- Then, the server sends the role for each client ```NEED VERIFICATION```
   - All the hosts are triggering ```FATAL ERROR```. We need to check if the current implementation shall be sending the clients to this state (keep in mind that this branch doesn't provide the proper client-side implementation).

image
image

### Logs
```log
[29-05-2024 10:23:04] [SERVER LOG] New connection from 127.0.0.1 on socket 308
[29-05-2024 10:23:04] [SERVER LOG] Message received: join
[29-05-2024 10:23:04] [SERVER LOG] Join request detected
[29-05-2024 10:23:04] [SERVER LOG] Current value of i: 308
[29-05-2024 10:23:04] [SERVER LOG] Changing state to LOBBY
[29-05-2024 10:23:04] [CLIENT LOG] Bytes received: 512
[29-05-2024 10:23:04] [CLIENT LOG] Received: mainhost
[29-05-2024 10:23:05] [SERVER LOG] New connection from 127.0.0.1 on socket 324
[29-05-2024 10:23:05] [SERVER LOG] Message received: join
[29-05-2024 10:23:05] [SERVER LOG] Join request detected
[29-05-2024 10:23:05] [SERVER LOG] Current value of i: 324
[29-05-2024 10:23:05] [CLIENT LOG] Bytes received: 512
[29-05-2024 10:23:05] [CLIENT LOG] Received: lobby
[29-05-2024 10:23:06] [SERVER LOG] New connection from 127.0.0.1 on socket 320
[29-05-2024 10:23:06] [SERVER LOG] Message received: join
[29-05-2024 10:23:06] [SERVER LOG] Join request detected
[29-05-2024 10:23:06] [SERVER LOG] Current value of i: 320
[29-05-2024 10:23:06] [CLIENT LOG] Bytes received: 512
[29-05-2024 10:23:06] [CLIENT LOG] Received: lobby
[29-05-2024 10:23:17] [SERVER LOG] Message received: namePlayer3
[29-05-2024 10:23:46] [SERVER LOG] Message received: nameClient2
[29-05-2024 10:23:56] [SERVER LOG] Message received: initMainHost
[29-05-2024 10:23:56] [SERVER LOG] Invalid number of players
[29-05-2024 10:23:56] [SERVER LOG] Current value of i: 308
[29-05-2024 10:23:56] [CLIENT LOG] Bytes received: 512
[29-05-2024 10:23:56] [CLIENT LOG] Received: mainhost
[29-05-2024 10:24:39] [SERVER LOG] New connection from 127.0.0.1 on socket 336
[29-05-2024 10:24:39] [SERVER LOG] Message received: join
[29-05-2024 10:24:39] [SERVER LOG] Join request detected
[29-05-2024 10:24:39] [SERVER LOG] Current value of i: 336
[29-05-2024 10:24:43] [SERVER LOG] Message received: nameClient4
[29-05-2024 10:24:47] [SERVER LOG] New connection from 127.0.0.1 on socket 340
[29-05-2024 10:24:47] [SERVER LOG] Message received: join
[29-05-2024 10:24:47] [SERVER LOG] Join request detected
[29-05-2024 10:24:47] [SERVER LOG] Current value of i: 340
[29-05-2024 10:24:50] [SERVER LOG] Message received: nameClient5
[29-05-2024 10:24:54] [SERVER LOG] New connection from 127.0.0.1 on socket 312
[29-05-2024 10:24:54] [SERVER LOG] Message received: join
[29-05-2024 10:24:54] [SERVER LOG] Join request detected
[29-05-2024 10:24:54] [SERVER LOG] Current value of i: 312
[29-05-2024 10:24:57] [SERVER LOG] Message received: nameClient6
[29-05-2024 10:25:09] [SERVER LOG] New connection from 127.0.0.1 on socket 332
[29-05-2024 10:25:09] [SERVER LOG] Message received: join
[29-05-2024 10:25:09] [SERVER LOG] Join request detected
[29-05-2024 10:25:09] [SERVER LOG] Current value of i: 332
[29-05-2024 10:25:11] [SERVER LOG] Message received: nameClient7
[29-05-2024 10:25:23] [SERVER LOG] Message received: initMainhost
[29-05-2024 10:25:23] [SERVER LOG] Invalid number of players
[29-05-2024 10:25:23] [SERVER LOG] Current value of i: 308
[29-05-2024 10:25:23] [CLIENT LOG] Bytes received: 512
[29-05-2024 10:25:23] [CLIENT LOG] Received: mainhost
[29-05-2024 10:25:36] [SERVER LOG] New connection from 127.0.0.1 on socket 348
[29-05-2024 10:25:36] [SERVER LOG] Message received: join
[29-05-2024 10:25:36] [SERVER LOG] Join request detected
[29-05-2024 10:25:36] [SERVER LOG] Current value of i: 348
[29-05-2024 10:25:39] [SERVER LOG] Message received: nameClient8
[29-05-2024 10:25:42] [SERVER LOG] New connection from 127.0.0.1 on socket 352
[29-05-2024 10:25:42] [SERVER LOG] Message received: join
[29-05-2024 10:25:42] [SERVER LOG] Join request detected
[29-05-2024 10:25:42] [SERVER LOG] Current value of i: 352
[29-05-2024 10:25:44] [SERVER LOG] Message received: nameClient9
[29-05-2024 10:25:59] [SERVER LOG] Message received: initMainhost
[29-05-2024 10:25:59] [SERVER LOG] Init request detected
[29-05-2024 10:25:59] [SERVER LOG] Current value of fdmax: 352
[29-05-2024 10:25:59] [SERVER LOG] Current value of i: 308
[29-05-2024 10:25:59] [CLIENT LOG] Bytes received: 512
12
[29-05-2024 10:25:59] [CLIENT LOG] Received: start
[29-05-2024 10:25:59] [SERVER LOG] Current value of i: 320
[29-05-2024 10:25:59] [SERVER LOG] Current value of i: 324
[29-05-2024 10:25:59] [CLIENT LOG] Bytes received: 512
[29-05-2024 10:25:59] [CLIENT LOG] Received: start
i: 332
[29-05-2024 10:25:59] [CLIENT LOG] Received: start
[29-05-2024 10:25:59] [SERVER LOG] Current value of i: 336
[29-05-2024 10:25:59] [SERVER LOG] Current value of i: 340
[29-05-2024 10:25:59] [SERVER LOG] Current value of i: 348
[29-05-2024 10:25:59] [SERVER LOG] Current value of i: 352
[29-05-2024 10:25:59] [SERVER LOG] Current value of i: 320
[29-05-2024 10:25:59] [SERVER LOG] Sending Role for all 
[29-05-2024 10:25:59] [SERVER LOG] Current value of i: 324
[29-05-2024 10:25:59] [SERVER LOG] Sending Role for all 
[29-05-2024 10:25:59] [SERVER LOG] Current value of i: 336
[29-05-2024 10:25:59] [SERVER LOG] Sending Role for all 
[29-05-2024 10:25:59] [SERVER LOG] Current value of i: 340
[29-05-2024 10:25:59] [SERVER LOG] Sending Role for all 
[29-05-2024 10:25:59] [SERVER LOG] Current value of i: 312
[29-05-2024 10:25:59] [SERVER LOG] Sending Role for all 
[29-05-2024 10:25:59] [SERVER LOG] Current value of i: 332
[29-05-2024 10:25:59] [SERVER LOG] Sending Role for all 
[29-05-2024 10:25:59] [SERVER LOG] Current value of i: 348
[29-05-2024 10:25:59] [SERVER LOG] Sending Role for all 
[29-05-2024 10:25:59] [SERVER LOG] Current value of i: 352
[29-05-2024 10:25:59] [SERVER LOG] Sending Role for all 
[29-05-2024 10:25:59] [CLIENT LOG] Changing state to NIGHT
[29-05-2024 10:25:59] [CLIENT LOG] Bytes received: 512
[29-05-2024 10:25:59] [CLIENT LOG] Received: role
[29-05-2024 10:25:59] [CLIENT LOG] Changing state to NIGHT
[29-05-2024 10:25:59] [CLIENT LOG] Bytes received: 512
[29-05-2024 10:25:59] [CLIENT LOG] Received: role
[29-05-2024 10:25:59] [SERVER LOG] Current value of i: 308
[29-05-2024 10:25:59] [SERVER LOG] Sending Role for all 
[29-05-2024 10:26:00] [SERVER LOG] Changing state to NIGHT
[29-05-2024 10:26:00] [CLIENT LOG] Changing state to NIGHT
[29-05-2024 10:26:00] [CLIENT LOG] Bytes received: 512
[29-05-2024 10:26:00] [CLIENT LOG] Received: role
```

### Test batch 2
- Server avoids duplicated names ```FAILED```
   - Not implemented with the last commit.
  
image

### Logs
```log
[29-05-2024 10:41:09] [SERVER LOG] New connection from 127.0.0.1 on socket 312
[29-05-2024 10:41:09] [SERVER LOG] Message received: join
[29-05-2024 10:41:09] [SERVER LOG] Join request detected
[29-05-2024 10:41:09] [SERVER LOG] Current value of i: 312
[29-05-2024 10:41:09] [SERVER LOG] Changing state to LOBBY
[29-05-2024 10:41:09] [CLIENT LOG] Bytes received: 512
[29-05-2024 10:41:09] [CLIENT LOG] Received: mainhost
[29-05-2024 10:41:10] [SERVER LOG] New connection from 127.0.0.1 on socket 320
[29-05-2024 10:41:10] [SERVER LOG] Message received: join
[29-05-2024 10:41:10] [SERVER LOG] Join request detected
[29-05-2024 10:41:10] [SERVER LOG] Current value of i: 320
[29-05-2024 10:41:10] [CLIENT LOG] Bytes received: 512
[29-05-2024 10:41:10] [CLIENT LOG] Received: lobby
[29-05-2024 10:41:11] [SERVER LOG] New connection from 127.0.0.1 on socket 324
[29-05-2024 10:41:11] [SERVER LOG] Message received: join
[29-05-2024 10:41:11] [SERVER LOG] Join request detected
[29-05-2024 10:41:11] [SERVER LOG] Current value of i: 324
[29-05-2024 10:41:11] [CLIENT LOG] Bytes received: 512
[29-05-2024 10:41:11] [CLIENT LOG] Received: lobby
[29-05-2024 10:41:19] [SERVER LOG] Message received: nameName
[29-05-2024 10:41:24] [SERVER LOG] Message received: nameName
```

**Comment by dalopezt** [comment]
@HAXHER Please attend the ```FAILED``` and ```NEED VERIFICATION``` points exposed in the previous comment. Make the corresponding commit. I'll be re-executing the same test cases. Once all of them passes correctly, we'll continue with the merging.

Kind regards.

**Review by dalopezt — CHANGES_REQUESTED** [review]
Check the pull request message thread to see which functions should be fixed.

**Review by buronsuave — CHANGES_REQUESTED** [review]
Same as dalopezt

**Pull request merged**
